### ISSUE TITLE
Controller validation: WT901

### ISSUE THREAD

**Issue by twdragon** [ElettraSciComp/witmotion_IMU_QT#2]
# Validation status
- Data acquisition: :heavy_check_mark: 
- Calibration:  :heavy_check_mark: 
- Baudrate change: :heavy_check_mark: 
- Polling interval change:  :heavy_check_mark: 
- Biases setup: :heavy_check_mark: - hacked for Acceleration bias setup, Angular velocities and Magnetic field biases are WIP

# Conclusion
Witmotion's vendor documentation seems non-plausible. Waiting for confirmation from the vendor

**Comment by twdragon** [comment]
@tohax выяснил у китайцев насчет сенсоров 9 серии. Для того, чтобы там стала доступна конфигурация, нужно передать "волшебную" команду для РАЗБЛОКИРОВКИ(!) регистров настройки:

`FF AA 69 88 B5`

Сенсоры 3 серии работают без нее. Для 9-й добавляю сейчас.

**Comment by tohax** [comment]
Отлично! Жду commit.

**Comment by twdragon** [comment]
@tohax скоро подниму версию в репозитории для ROS. Пока, буду очень признателен, если потестите свой датчик, задавая разные скорости передачи и частоты отдачи, с помощью приложения `witmotionctl-wt901`, его возможностей уже хватает для тестов

**Comment by tohax** [comment]
It's alive! Работает! Программа, которую я использую, теперь не ругается на низкую частоту. Ей нужно 150гц минимум, значит wt901c выдает больше. Продолжу тестировать. Благодарю за проделанную работу!

**Comment by twdragon** [comment]
@tohax ,благодарю за тест! Вместе победим!
